### PR TITLE
Fix soapysdr Trun on/Turn off sigterm

### PR DESCRIPTION
**Pull request by wingrime**
When I do fast turn on/turn off I have crash in libsoapysdr

### CODE REVIEW

**Comment by AlexandreRouma** [comment]
Hi,

That's a strange issue because the start/stop functions are synchonous and already gated by a variable in the main software. (aka, the stop function can only be called after the start and vice versa)

This means it's likely a bug in SoapySDR itself.

Have your modifications fixed the issue for your?

Best regards

**Comment by wingrime** [comment]
Synchronous thread does not means soapySDR is not (or libsdrplay behind it)


My stack trace:
```
raise 0x00007ffff6875615
abort 0x00007ffff685e862
__gnu_cxx::__verbose_terminate_handler 0x00007ffff6ab186a
__cxxabiv1::__terminate 0x00007ffff6abdd9a
__cxa_call_terminate 0x00007ffff6abcd4a
__cxxabiv1::__gxx_personality_v0 0x00007ffff6abd722
_Unwind_RaiseException_Phase2 0x00007ffff6a116b0
_Unwind_RaiseException 0x00007ffff6a11d42
__cxxabiv1::__cxa_throw 0x00007ffff6abe09f
<unknown> 0x00007fffd03145c7
SoapySDRPlay::~SoapySDRPlay() 0x00007fffd031a92e
SoapySDRPlay::~SoapySDRPlay() 0x00007fffd031a98a
SoapySDR::Device::unmake(SoapySDR::Device*) 0x00007fffd04e93d4
SoapyModule::stop main.cpp:257
drawWindow main_window.cpp:415
sdrpp_main core.cpp:269
main main.cpp:5
__libc_start_main 0x00007ffff6860152
_start 0x000055555555506e
```

**Comment by wingrime** [comment]
and why some modules have such check and some does not have?

**Comment by wingrime** [comment]
seems I does not test hard enough (fast turn on,turn off)

bug persists

**Comment by AlexandreRouma** [comment]
yes, this is likely a soapy bug
the library is supposed to be able to handle instantanious start/stop

if you have the time, I recommend writing a minimal broken example and submit it to the SoapySDR team.
aka a small c++ file that just starts and stops a devices instantly and crashes
to allow the SoapySDR authors to debug the issue.

Best regards,
Alex.

**Pull request closed without merging**
