### PR TITLE
Add Republic of Korea BandPlan

### PR DESCRIPTION
**Pull request by bsy0317**
Add Republic of Korea BandPlan.
It's not the Democratic People's Republic of Korea!

### CODE REVIEW

**Comment by AlexandreRouma** [comment]
SDR++ doesn't support displaying characters outside the latin alphabet so thi bandplan won't display properly. Also there are some typos in the band types (eg. `marin` instead of `marine`)

**Comment by bsy0317** [comment]
Hello! I've made the requested changes and submitted a pull request. Please review it. :)

**Comment by AlexandreRouma** [comment]
Alright, just one last thing. The indentation has to be 4 spaces like it was before.

**Comment by bsy0317** [comment]
Thank you for your quick response :)

**Comment by bsy0317** [comment]
corrected that

**Comment by bsy0317** [comment]
In addition, this is designated by the Korea Radio Administration

**Pull request merged**
