### PR TITLE
feat: allow several fractional scaling options

### PR DESCRIPTION
**Pull request by DuMOHsmol**
Hi, thanks for the great software!

I've got a laptop with 14" FullHD display. 100% scale is too small for it, and 200% is too huge. So, I've decided to add several fractional scaling options. They seem to work well enough, got no glitches while playing around with my RTL-SDR.

### CODE REVIEW

**Comment by AlexandreRouma** [comment]
There is a good reason why those resolutions are not available. They cause some widgets to be misaligned. Until these things are fixed I cannot enable those scaling options.

**Comment by DuMOHsmol** [comment]
Got it, thanks. Shall I open the issue for it then? I could not find anything related to fractional scaling in the bug tracker.

And which widgets are broken exactly? Maybe I could try checking them as well.

**Comment by AlexandreRouma** [comment]
Create an issue yes. Don't bother with trying to fix the widgets. Hacking all of them to work properly is not a solution, it needs to be a more general change to how scaling is done in the first place.

**Comment by DuMOHsmol** [comment]
Ok, created it: https://github.com/AlexandreRouma/SDRPlusPlus/issues/1116

**Pull request closed without merging**
