### PR TITLE
Update Dear ImGui to 1.85

### PR DESCRIPTION
**Pull request by aeburriel**
Update ImGui to 1.85, solves ticket #529

### CODE REVIEW

**Comment by aeburriel** [comment]
Because in ImGui 1.85 OpenGL is initialized by the embedded loader:
https://github.com/ocornut/imgui/issues/4445

If you review the demos you'll see it's now the standard way.

**Comment by AlexandreRouma** [comment]
Has this been properly tested yet?
I afraid of switching to this embedded loader without being sure it still handles OpenGL 2.0 (ES) properly on raspberry pi boards

**Comment by aeburriel** [comment]
Nope, only in a couple of Linux/amd64.
Unfortunately I don't have access to other architectures.

**Comment by AlexandreRouma** [comment]
Alright, I'm gonna wait for this branch to be tested on other platforms before merging.
But before, a few things:
1) If glew is not longer needed, it should be removed from the core CMakeLists.txt
2) It's important to check if this change has any performance impact.

**Comment by aeburriel** [comment]
Code updated as follows:
1. Re-added an include required for linking properly in Windows which I removed by accident.
2. Removed all GLEW dependencies and updated readme.

Tested on Linux/amd64 & Windows/x64.
About the performance, I agree it should be tested in low-end devices. Dear ImGui update is mostly bugfixes, according to its changelog. Graphics access remains the same, the only difference is the way OpenGL is initialized.

**Comment by AlexandreRouma** [comment]
Alright, i'll check that the ImGui update was done correctly, some settings had to be changed in imconfig for the last version

**Comment by AlexandreRouma** [comment]
Looks like trying to get GL from pkg-config files on MacOS, not really sure what the cleanest way to go about it is at this point.

**Comment by AlexandreRouma** [comment]
Alright, I've done this along with other changes in the pull request I just merge.
Please confirm that the latest commit fixes the issues you were having and re-open if it doesn't

**Pull request closed without merging**
