### PR TITLE
Add bandplan for ireland

### PR DESCRIPTION
**Pull request by Oskar-Dudek**
Created a bandplan for ireland

### CODE REVIEW

**Review by Oskar-Dudek — COMMENTED** [review]
so do i open a pull request with the new code that has formatting fixed (hopefully)? or did you already fix it?

**Comment by AlexandreRouma** [comment]
No I fixed it myself and it's merged

**Comment by Oskar-Dudek** [comment]
Thank you

**Comment by Oskar-Dudek** [comment]
And one more thing, if i learn json i will come back tommorow to add more stuff to the irish band plan

**Pull request merged**
